name: Moxie.Build
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6173765072599053
title: Moxie.Build - Web Development Platform that Keeps It Simple
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffcd9'
    - '#7a390f'
    - '#d3c69a'
    - '#6baeb7'
    - '#160a0a'
  brandStrength: 0.2645599734969437
  lightness: 0.4200988404918462
  saturation: 0.3732479214668274
  rhythmicContrast: 0.42739554052241147
purpose: []
